"""inital

Revision ID: 0692815e71f9
Revises: 
Create Date: 2022-08-29 11:08:27.496190

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0692815e71f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dept', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_dept'), ['dept'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_person_id'), ['id'], unique=False)

    op.create_table('balance',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(scale=3), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_id'), ['id'], unique=False)

    op.create_table('movement',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Numeric(scale=3), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movement_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_movement_id'), ['id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id'))

    op.drop_table('user')
    with op.batch_alter_table('movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movement_id'))
        batch_op.drop_index(batch_op.f('ix_movement_actor'))

    op.drop_table('movement')
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_id'))

    op.drop_table('balance')
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_id'))
        batch_op.drop_index(batch_op.f('ix_person_email'))
        batch_op.drop_index(batch_op.f('ix_person_dept'))

    op.drop_table('person')
    # ### end Alembic commands ###
